package madoku.craft;

import madoku.craft.armor.MadokuArmor;
import madoku.craft.attributes.MadokuAttributes;
import madoku.craft.clock.MadokuClock;
import madoku.craft.clock.MadokuTicks;
import madoku.craft.composter.system.MadokuComposter;
import madoku.craft.config.StaticJsonSystem;
import madoku.craft.debug.MadokuDebug;
import madoku.craft.difficulty.system.MadokuDifficulty;
import madoku.craft.farming.system.MadokuFarming;
import madoku.craft.health.MadokuHealth;
import madoku.craft.hunger.MadokuHunger;
import madoku.craft.item.system.MadokuItem;
import madoku.craft.itemstack.system.MadokuItemStack;
import madoku.craft.levels.MadokuLevels;
import madoku.craft.luck.MadokuLuck;
import madoku.craft.luck.MadokuPlacedBlocks;
import madoku.craft.mob.system.MadokuMob;
import madoku.craft.network.HungerHudSync;
import madoku.craft.network.WorldDifficultySync;
import madoku.craft.network.WorldSeasonSync;
import madoku.craft.network.WorldTimeSync;
import madoku.craft.oxygen.MadokuOxygen;
import madoku.craft.rarity.MadokuRarity;
import madoku.craft.scheduler.MadokuScheduler;
import madoku.craft.season.MadokuSeason;
import madoku.craft.smelting.system.MadokuSmeltingManager;
import madoku.craft.time.MadokuSleep;
import madoku.craft.time.MadokuTime;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.entity.event.v1.EntitySleepEvents;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents;

public class MadokuCraft implements ModInitializer {
	public static final String MOD_ID = "madoku-craft";

	@Override
	public void onInitialize() {
		StaticJsonSystem.initialize();
		MadokuSmeltingManager.initialize();
		MadokuDebug.initialize();
		MadokuDifficulty.initialize();
		MadokuTime.initialize();
		MadokuSeason.initialize();
		MadokuItem.initialize();
		MadokuComposter.initialize();
		MadokuFarming.initialize();
		MadokuMob.initialize();
		MadokuRarity.initialize();
		MadokuItemStack.initialize();
		MadokuAttributes.initialize();
		MadokuPlacedBlocks.initialize();
		MadokuArmor.initialize();
		MadokuHealth.initialize();
		MadokuHunger.initialize();
		MadokuOxygen.initialize();
		MadokuLevels.initialize();
		MadokuLuck.initialize();
		EntitySleepEvents.ALLOW_RESETTING_TIME.register(player -> !MadokuTime.isEnabled());
		WorldTimeSync.initialize();
		WorldDifficultySync.initialize();
		WorldSeasonSync.initialize();
		HungerHudSync.initialize();

		ServerLifecycleEvents.SERVER_STARTED.register(server -> {
			MadokuDebug.resetSession();
			MadokuTicks.reset();
			MadokuClock.reset();
			MadokuSleep.reset();
			MadokuTime.reset();
			MadokuSeason.reset();
			MadokuFarming.reset();
			MadokuItemStack.reset();
			MadokuPlacedBlocks.reset();
			MadokuHealth.reset();
			MadokuHunger.reset();
			MadokuOxygen.reset();
			MadokuLevels.reset();
			MadokuScheduler.reset();
			MadokuScheduler.loadPersistedData(server);
			MadokuTime.loadPersistedData(server);
			MadokuSeason.loadPersistedData(server);
			MadokuFarming.loadPersistedData(server);
			MadokuPlacedBlocks.loadPersistedData(server);
			MadokuSeason.onServerStarted(server);
			MadokuFarming.onServerStarted(server);
			MadokuSmeltingManager.onServerStarted();
			MadokuHealth.loadPersistedData(server);
			MadokuHunger.loadPersistedData(server);
			MadokuOxygen.loadPersistedData(server);
			MadokuLevels.loadPersistedData(server);
			MadokuItemStack.loadPersistedData(server);
			MadokuItem.onServerStarted();
			MadokuMob.onServerStarted(server);
			MadokuDifficulty.onServerStarted(server);
			MadokuTime.update(server);
			WorldTimeSync.reset();
			WorldDifficultySync.reset();
			WorldSeasonSync.reset();
			WorldTimeSync.broadcastNow(server);
			WorldDifficultySync.broadcastNow(server);
			WorldSeasonSync.broadcastNow(server);
		});

		ServerLifecycleEvents.SERVER_STOPPED.register(server -> {
			MadokuTime.savePersistedData(server);
			MadokuSeason.savePersistedData(server);
			MadokuFarming.savePersistedData(server);
			MadokuScheduler.savePersistedData(server);
			MadokuPlacedBlocks.savePersistedData(server);
			MadokuHealth.savePersistedData(server);
			MadokuHunger.savePersistedData(server);
			MadokuOxygen.savePersistedData(server);
			MadokuLevels.savePersistedData(server);
			MadokuItemStack.savePersistedData(server);
			MadokuClock.reset();
			MadokuTicks.reset();
			MadokuSleep.reset();
			MadokuTime.reset();
			MadokuSeason.reset();
			MadokuFarming.reset();
			MadokuScheduler.reset();
			MadokuPlacedBlocks.reset();
			MadokuSmeltingManager.onServerStopped();
			MadokuDifficulty.onServerStopped();
			MadokuMob.onServerStopped();
			MadokuHealth.reset();
			MadokuHunger.reset();
			MadokuOxygen.reset();
			MadokuLevels.reset();
			MadokuItemStack.reset();
			WorldTimeSync.reset();
			WorldDifficultySync.reset();
			WorldSeasonSync.reset();
		});

		ServerTickEvents.END_SERVER_TICK.register(server -> {
			long tickIncrement = MadokuSleep.getTickIncrement(server);
			// Remap sleep / time-command jumps before any time-based tasks consume this tick.
			MadokuTime.update(server);
			MadokuTicks.advance(server, tickIncrement);
			MadokuFarming.onServerTickIncrement(server, tickIncrement);
			MadokuScheduler.autosavePersistedData(server);
			MadokuTime.autosavePersistedData(server);
			MadokuHealth.autosavePersistedData(server);
			MadokuHunger.autosavePersistedData(server);
			MadokuSeason.autosavePersistedData(server);
			MadokuFarming.autosavePersistedData(server);
			MadokuPlacedBlocks.autosavePersistedData(server);
			MadokuOxygen.autosavePersistedData(server);
			MadokuLevels.autosavePersistedData(server);
			MadokuItemStack.autosavePersistedData(server);
			MadokuTime.update(server);
			MadokuSeason.onServerTick(server);
			MadokuDifficulty.onServerTick(server);
			MadokuMob.onServerTick(server);
			MadokuLevels.flushDirtySyncs(server);
			WorldTimeSync.broadcastIfChanged(server);
			WorldDifficultySync.broadcastIfChanged(server);
			WorldSeasonSync.broadcastIfChanged(server);
		});
	}
}
